CREATE TABLE TBL_EMPRESA (
    ID_EMPRESA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    NOME VARCHAR2(100) NOT NULL,                                    
    CNPJ CHAR(14) NOT NULL UNIQUE,                                  
    EMAIL VARCHAR2(100) NOT NULL,                                  
    TELEFONE CHAR(10) NOT NULL                                      
);

SELECT * FROM TBL_EMPRESA;

CREATE TABLE TBL_USUARIO (
    ID_USUARIO NUMBER GENERATED BY DEFAULT AS IDENTITY, 
    NOME VARCHAR2(100) NOT NULL,                        
    CPF CHAR(11) NOT NULL UNIQUE,                      
    EMAIL VARCHAR2(255) NOT NULL,                       
    TELEFONE CHAR(11) NOT NULL,                         
    PRIMARY KEY (ID_USUARIO)                            
);

SELECT * FROM TBL_USUARIO;
